MAX_LEN_STRING = 100
MIN_LEN_STRING = 1
DEFAULT_INVESTED_AMOUNT = 0
DEFAULT_FULLY_INVESTED = False
LIFETIME_TOKEN = 3600
MIN_PASSWORD_LENGTH = 3


FORMAT = "%Y/%m/%d %H:%M:%S"
SHEET_ID = 0
ROW_COUNT = 100
COLUMN_COUNT = 3
