"""migration_name

Revision ID: 3f49a4978cb3
Revises: 974e38b66545
Create Date: 2025-02-12 16:24:31.720796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f49a4978cb3'
down_revision = '974e38b66545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
