"""First migration

Revision ID: 974e38b66545
Revises: 00215d020b5a
Create Date: 2024-06-30 02:47:54.192945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "974e38b66545"
down_revision = "00215d020b5a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
